target_dbms: "mysql"
database_name: "sqlcraft_radar_raw"
schema_path: "./data/mysql/radar/current_schema/raw_schema.sql"
max_connections: 1
db_config:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"